const countryCodes = {
    ad: {country: 'Andorra', ISO2: 'ad', CountryCode: '376'},
    ae: {country: 'United Arab Emirates', ISO2: 'ae', CountryCode: '971'},
    af: {country: 'Afghanistan', ISO2: 'af', CountryCode: '93'},
    ag: {country: 'Antigua and Barbuda', ISO2: 'ag', CountryCode: '1268'},
    ai: {country: 'Anguilla', ISO2: 'ai', CountryCode: '1264'},
    al: {country: 'Albania', ISO2: 'al', CountryCode: '355'},
    am: {country: 'Armenia', ISO2: 'am', CountryCode: '374'},
    an: {country: 'Netherlands Antilles', ISO2: 'an', CountryCode: '599'},
    ao: {country: 'Angola', ISO2: 'ao', CountryCode: '244'},
    ar: {country: 'Argentina', ISO2: 'ar', CountryCode: '54'},
    at: {country: 'Austria', ISO2: 'at', CountryCode: '43'},
    au: {country: 'Australia', ISO2: 'au', CountryCode: '61'},
    aw: {country: 'Aruba', ISO2: 'aw', CountryCode: '297'},
    az: {country: 'Azerbaijan', ISO2: 'az', CountryCode: '994'},
    ba: {country: 'Bosnia and Herzegovina', ISO2: 'ba', CountryCode: '387'},
    bb: {country: 'Barbados', ISO2: 'bb', CountryCode: '1246'},
    bd: {country: 'Bangladesh', ISO2: 'bd', CountryCode: '880'},
    be: {country: 'Belgium', ISO2: 'be', CountryCode: '32'},
    bf: {country: 'Burkina Faso', ISO2: 'bf', CountryCode: '226'},
    bg: {country: 'Bulgaria', ISO2: 'bg', CountryCode: '359'},
    bh: {country: 'Bahrain', ISO2: 'bh', CountryCode: '973'},
    bi: {country: 'Burundi', ISO2: 'bi', CountryCode: '257'},
    bj: {country: 'Benin', ISO2: 'bj', CountryCode: '229'},
    bm: {country: 'Bermuda', ISO2: 'bm', CountryCode: '1441'},
    bn: {country: 'Brunei', ISO2: 'bn', CountryCode: '673'},
    bo: {country: 'Bolivia', ISO2: 'bo', CountryCode: '591'},
    br: {country: 'Brazil', ISO2: 'br', CountryCode: '55'},
    bs: {country: 'Bahamas', ISO2: 'bs', CountryCode: '1242'},
    bt: {country: 'Bhutan', ISO2: 'bt', CountryCode: '975'},
    bw: {country: 'Botswana', ISO2: 'bw', CountryCode: '267'},
    by: {country: 'Belarus', ISO2: 'by', CountryCode: '375'},
    bz: {country: 'Belize', ISO2: 'bz', CountryCode: '501'},
    ca: {country: 'Canada', ISO2: 'ca', CountryCode: '1'},
    cd: {country: 'Democratic Republic of the Congo', ISO2: 'cd', CountryCode: '243'},
    cf: {country: 'Central African Republic', ISO2: 'cf', CountryCode: '236'},
    cg: {country: 'Republic of the Congo', ISO2: 'cg', CountryCode: '242'},
    ch: {country: 'Switzerland', ISO2: 'ch', CountryCode: '41'},
    ci: {country: 'Ivory Coast', ISO2: 'ci', CountryCode: '225'},
    ck: {country: 'Cook Islands', ISO2: 'ck', CountryCode: '682'},
    cl: {country: 'Chile', ISO2: 'cl', CountryCode: '56'},
    cm: {country: 'Cameroon', ISO2: 'cm', CountryCode: '237'},
    cn: {country: 'Republic of China', ISO2: 'cn', CountryCode: '86'},
    co: {country: 'Colombia', ISO2: 'co', CountryCode: '57'},
    cr: {country: 'Costa Rica', ISO2: 'cr', CountryCode: '506'},
    cu: {country: 'Cuba', ISO2: 'cu', CountryCode: '53'},
    cv: {country: 'Cape Verde', ISO2: 'cv', CountryCode: '238'},
    cx: {country: 'Christmas Island', ISO2: 'cx', CountryCode: '61'},
    cy: {country: 'Cyprus', ISO2: 'cy', CountryCode: '357'},
    cz: {country: 'Czech Republic', ISO2: 'cz', CountryCode: '420'},
    de: {country: 'Germany', ISO2: 'de', CountryCode: '49'},
    dj: {country: 'Djibouti', ISO2: 'dj', CountryCode: '253'},
    dk: {country: 'Denmark', ISO2: 'dk', CountryCode: '45'},
    dm: {country: 'Dominica', ISO2: 'dm', CountryCode: '1767'},
    do: {country: 'Dominican Republic', ISO2: 'do', CountryCode: '1809'},
    dz: {country: 'Algeria', ISO2: 'dz', CountryCode: '213'},
    ec: {country: 'Ecuador', ISO2: 'ec', CountryCode: '593'},
    ee: {country: 'Estonia', ISO2: 'ee', CountryCode: '372'},
    eg: {country: 'Egypt', ISO2: 'eg', CountryCode: '20'},
    er: {country: 'Eritrea', ISO2: 'er', CountryCode: '291'},
    es: {country: 'Spain', ISO2: 'es', CountryCode: '34'},
    et: {country: 'Ethiopia', ISO2: 'et', CountryCode: '251'},
    fi: {country: 'Finland', ISO2: 'fi', CountryCode: '358'},
    fj: {country: 'Fiji', ISO2: 'fj', CountryCode: '679'},
    fk: {country: 'Falkland Islands', ISO2: 'fk', CountryCode: '500'},
    fm: {country: 'Micronesia', ISO2: 'fm', CountryCode: '691'},
    fo: {country: 'Faroe Islands', ISO2: 'fo', CountryCode: '298'},
    fr: {country: 'Réunion', ISO2: 'fr', CountryCode: '262'},
    ga: {country: 'Gabon', ISO2: 'ga', CountryCode: '241'},
    gb: {country: 'United Kingdom', ISO2: 'gb', CountryCode: '44'},
    gd: {country: 'Grenada', ISO2: 'gd', CountryCode: '1473'},
    ge: {country: 'Georgia', ISO2: 'ge', CountryCode: '995'},
    gh: {country: 'Ghana', ISO2: 'gh', CountryCode: '233'},
    gi: {country: 'Gibraltar', ISO2: 'gi', CountryCode: '350'},
    gl: {country: 'Greenland', ISO2: 'gl', CountryCode: '299'},
    gm: {country: 'Gambia', ISO2: 'gm', CountryCode: '220'},
    gn: {country: 'Guinea', ISO2: 'gn', CountryCode: '224'},
    gq: {country: 'Equatorial Guinea', ISO2: 'gq', CountryCode: '240'},
    gr: {country: 'Greece', ISO2: 'gr', CountryCode: '30'},
    gt: {country: 'Guatemala', ISO2: 'gt', CountryCode: '502'},
    gw: {country: 'Guinea-Bissau', ISO2: 'gw', CountryCode: '245'},
    gy: {country: 'Guyana', ISO2: 'gy', CountryCode: '592'},
    hk: {country: 'Hong Kong', ISO2: 'hk', CountryCode: '852'},
    hn: {country: 'Honduras', ISO2: 'hn', CountryCode: '504'},
    hr: {country: 'Croatia', ISO2: 'hr', CountryCode: '385'},
    ht: {country: 'Haiti', ISO2: 'ht', CountryCode: '509'},
    hu: {country: 'Hungary', ISO2: 'hu', CountryCode: '36'},
    id: {country: 'Indonesia', ISO2: 'id', CountryCode: '62'},
    ie: {country: 'Ireland', ISO2: 'ie', CountryCode: '353'},
    il: {country: 'Israel', ISO2: 'il', CountryCode: '972'},
    in: {country: 'India', ISO2: 'in', CountryCode: '91'},
    io: {country: 'Diego Garcia', ISO2: 'io', CountryCode: '246'},
    iq: {country: 'Iraq', ISO2: 'iq', CountryCode: '964'},
    ir: {country: 'Iran', ISO2: 'ir', CountryCode: '98'},
    it: {country: 'Italy', ISO2: 'it', CountryCode: '39'},
    jm: {country: 'Jamaica', ISO2: 'jm', CountryCode: '1876'},
    jo: {country: 'Jordan', ISO2: 'jo', CountryCode: '962'},
    jp: {country: 'Japan', ISO2: 'jp', CountryCode: '81'},
    ke: {country: 'Kenya', ISO2: 'ke', CountryCode: '254'},
    kg: {country: 'Kyrgyzstan', ISO2: 'kg', CountryCode: '996'},
    kh: {country: 'Cambodia', ISO2: 'kh', CountryCode: '855'},
    ki: {country: 'Kiribati', ISO2: 'ki', CountryCode: '686'},
    km: {country: 'Comoros', ISO2: 'km', CountryCode: '269'},
    kn: {country: 'St. Kitts and Nevis', ISO2: 'kn', CountryCode: '1869'},
    kp: {country: 'North Korea', ISO2: 'kp', CountryCode: '850'},
    kr: {country: 'South Korea', ISO2: 'kr', CountryCode: '82'},
    kw: {country: 'Kuwait', ISO2: 'kw', CountryCode: '965'},
    ky: {country: 'Cayman Islands', ISO2: 'ky', CountryCode: '1345'},
    kz: {country: 'Kazakhstan', ISO2: 'kz', CountryCode: '7'},
    la: {country: 'Laos', ISO2: 'la', CountryCode: '856'},
    lb: {country: 'Lebanon', ISO2: 'lb', CountryCode: '961'},
    lc: {country: 'St. Lucia', ISO2: 'lc', CountryCode: '1758'},
    li: {country: 'Liechtenstein', ISO2: 'li', CountryCode: '423'},
    lk: {country: 'Sri Lanka', ISO2: 'lk', CountryCode: '94'},
    lr: {country: 'Liberia', ISO2: 'lr', CountryCode: '231'},
    ls: {country: 'Lesotho', ISO2: 'ls', CountryCode: '266'},
    lt: {country: 'Lithuania', ISO2: 'lt', CountryCode: '370'},
    lu: {country: 'Luxembourg', ISO2: 'lu', CountryCode: '352'},
    lv: {country: 'Latvia', ISO2: 'lv', CountryCode: '371'},
    ly: {country: 'Libya', ISO2: 'ly', CountryCode: '218'},
    ma: {country: 'Morocco', ISO2: 'ma', CountryCode: '212'},
    mc: {country: 'Monaco', ISO2: 'mc', CountryCode: '377'},
    md: {country: 'Moldova', ISO2: 'md', CountryCode: '373'},
    me: {country: 'Montenegro', ISO2: 'me', CountryCode: '382'},
    mg: {country: 'Madagascar', ISO2: 'mg', CountryCode: '261'},
    mh: {country: 'Marshall Islands', ISO2: 'mh', CountryCode: '692'},
    mk: {country: 'Macedonia', ISO2: 'mk', CountryCode: '389'},
    ml: {country: 'Mali', ISO2: 'ml', CountryCode: '223'},
    mm: {country: 'Burma', ISO2: 'mm', CountryCode: '95'},
    mn: {country: 'Mongolia', ISO2: 'mn', CountryCode: '976'},
    mo: {country: 'Macau', ISO2: 'mo', CountryCode: '853'},
    mp: {country: 'Mariana Island', ISO2: 'mp', CountryCode: '1670'},
    mr: {country: 'Mauritania', ISO2: 'mr', CountryCode: '222'},
    ms: {country: 'Montserrat', ISO2: 'ms', CountryCode: '1664'},
    mt: {country: 'Malta', ISO2: 'mt', CountryCode: '356'},
    mu: {country: 'Mauritius', ISO2: 'mu', CountryCode: '230'},
    mv: {country: 'Maldives', ISO2: 'mv', CountryCode: '960'},
    mw: {country: 'Malawi', ISO2: 'mw', CountryCode: '265'},
    mx: {country: 'Mexico', ISO2: 'mx', CountryCode: '52'},
    my: {country: 'Malaysia', ISO2: 'my', CountryCode: '60'},
    mz: {country: 'Mozambique', ISO2: 'mz', CountryCode: '258'},
    na: {country: 'Namibia', ISO2: 'na', CountryCode: '264'},
    nc: {country: 'New Caledonia', ISO2: 'nc', CountryCode: '687'},
    ne: {country: 'Niger', ISO2: 'ne', CountryCode: '227'},
    ng: {country: 'Nigeria', ISO2: 'ng', CountryCode: '234'},
    ni: {country: 'Nicaragua', ISO2: 'ni', CountryCode: '505'},
    nl: {country: 'Netherlands', ISO2: 'nl', CountryCode: '31'},
    no: {country: 'Norway', ISO2: 'no', CountryCode: '47'},
    np: {country: 'Nepal', ISO2: 'np', CountryCode: '977'},
    nr: {country: 'Nauru', ISO2: 'nr', CountryCode: '674'},
    nu: {country: 'Niue', ISO2: 'nu', CountryCode: '683'},
    nz: {country: 'New Zealand', ISO2: 'nz', CountryCode: '64'},
    om: {country: 'Oman', ISO2: 'om', CountryCode: '968'},
    pa: {country: 'Panama', ISO2: 'pa', CountryCode: '507'},
    pe: {country: 'Peru', ISO2: 'pe', CountryCode: '51'},
    ph: {country: 'Philippines', ISO2: 'ph', CountryCode: '63'},
    pk: {country: 'Pakistan', ISO2: 'pk', CountryCode: '92'},
    pl: {country: 'Poland', ISO2: 'pl', CountryCode: '48'},
    pm: {country: 'Saint-Pierre and Miquelon', ISO2: 'pm', CountryCode: '508'},
    pr: {country: 'Puerto Rico', ISO2: 'pr', CountryCode: '1'},
    ps: {country: 'Palestine', ISO2: 'ps', CountryCode: '970'},
    pt: {country: 'Portugal', ISO2: 'pt', CountryCode: '351'},
    pw: {country: 'Palau', ISO2: 'pw', CountryCode: '680'},
    py: {country: 'Paraguay', ISO2: 'py', CountryCode: '595'},
    qa: {country: 'Qatar', ISO2: 'qa', CountryCode: '974'},
    ro: {country: 'Romania', ISO2: 'ro', CountryCode: '40'},
    rs: {country: 'Serbia', ISO2: 'rs', CountryCode: '381'},
    ru: {country: 'Russia', ISO2: 'ru', CountryCode: '7'},
    rw: {country: 'Rwanda', ISO2: 'rw', CountryCode: '250'},
    sa: {country: 'Saudi Arabia', ISO2: 'sa', CountryCode: '966'},
    sb: {country: 'Solomon Islands', ISO2: 'sb', CountryCode: '677'},
    sc: {country: 'Seychelles', ISO2: 'sc', CountryCode: '248'},
    sd: {country: 'Sudan', ISO2: 'sd', CountryCode: '249'},
    se: {country: 'Sweden', ISO2: 'se', CountryCode: '46'},
    sg: {country: 'Singapore', ISO2: 'sg', CountryCode: '65'},
    sh: {country: 'St. Helena', ISO2: 'sh', CountryCode: '290'},
    si: {country: 'Slovenia', ISO2: 'si', CountryCode: '386'},
    sk: {country: 'Slovakia', ISO2: 'sk', CountryCode: '421'},
    sl: {country: 'Sierra Leone', ISO2: 'sl', CountryCode: '232'},
    sm: {country: 'San Marino', ISO2: 'sm', CountryCode: '378'},
    sn: {country: 'Senegal', ISO2: 'sn', CountryCode: '221'},
    so: {country: 'Somalia', ISO2: 'so', CountryCode: '252'},
    sr: {country: 'Surinam', ISO2: 'sr', CountryCode: '597'},
    st: {country: 'São Tomé and Príncipe', ISO2: 'st', CountryCode: '239'},
    sv: {country: 'El Salvador', ISO2: 'sv', CountryCode: '503'},
    sy: {country: 'Syria', ISO2: 'sy', CountryCode: '963'},
    sz: {country: 'Swaziland', ISO2: 'sz', CountryCode: '268'},
    tc: {country: 'Turks and Caicos Islands', ISO2: 'tc', CountryCode: '1649'},
    td: {country: 'Chad', ISO2: 'td', CountryCode: '235'},
    tg: {country: 'Togo', ISO2: 'tg', CountryCode: '228'},
    th: {country: 'Thailand', ISO2: 'th', CountryCode: '66'},
    tj: {country: 'Tajikistan', ISO2: 'tj', CountryCode: '992'},
    tl: {country: 'East Timor', ISO2: 'tl', CountryCode: '670'},
    tm: {country: 'Turkmenistan', ISO2: 'tm', CountryCode: '993'},
    tn: {country: 'Tunisia', ISO2: 'tn', CountryCode: '216'},
    to: {country: 'Tonga', ISO2: 'to', CountryCode: '676'},
    tr: {country: 'Turkey', ISO2: 'tr', CountryCode: '90'},
    tt: {country: 'Trinidad and Tobago', ISO2: 'tt', CountryCode: '1868'},
    tv: {country: 'Tuvalu', ISO2: 'tv', CountryCode: '688'},
    tw: {country: 'Taiwan', ISO2: 'tw', CountryCode: '886'},
    tz: {country: 'Tanzania', ISO2: 'tz', CountryCode: '255'},
    ua: {country: 'Ukraine', ISO2: 'ua', CountryCode: '380'},
    ug: {country: 'Uganda', ISO2: 'ug', CountryCode: '256'},
    us: {country: 'United States', ISO2: 'us', CountryCode: '1'},
    uy: {country: 'Uruguay', ISO2: 'uy', CountryCode: '598'},
    uz: {country: 'Uzbekistan', ISO2: 'uz', CountryCode: '998'},
    va: {country: 'Vatican City', ISO2: 'va', CountryCode: '39'},
    vc: {country: 'St. Vincent and the Grenadines', ISO2: 'vc', CountryCode: '1784'},
    ve: {country: 'Venezuela', ISO2: 've', CountryCode: '58'},
    vg: {country: 'British Virgin Islands', ISO2: 'vg', CountryCode: '1284'},
    vi: {country: 'Virgin Islands', ISO2: 'vi', CountryCode: '1340'},
    vn: {country: 'Vietnam', ISO2: 'vn', CountryCode: '84'},
    vu: {country: 'Vanuatu', ISO2: 'vu', CountryCode: '678'},
    wf: {country: 'Wallis and Futuna', ISO2: 'wf', CountryCode: '681'},
    ws: {country: 'Samoa', ISO2: 'ws', CountryCode: '685'},
    xk: {country: 'Kosovo', ISO2: 'xk', CountryCode: '381'},
    ye: {country: 'Yemen', ISO2: 'ye', CountryCode: '967'},
    za: {country: 'South Africa', ISO2: 'za', CountryCode: '27'},
    zm: {country: 'Zambia', ISO2: 'zm', CountryCode: '260'},
    zw: {country: 'Zimbabwe', ISO2: 'zw', CountryCode: '263'},
};